using System.Text.Json;
using System.Text.Json.Nodes;
using BattleScribeSpec.BsRosterUiDriver;
using BattleScribeSpec.GameData;
using BattleScribeSpec.Protocol;
using BattleScribeSpec.Roster;
using BattleScribeSpec.XmlGen;

namespace BattleScribeSpec.BsGameDataUiDriver;

/// <summary>
/// Drives the BattleScribe desktop Data Editor UI via the bs-ui-java-agent.
/// <para>
/// <b>Architecture (hybrid UI driver pattern)</b>:
/// <list type="bullet">
///   <item><b>Mutations via UI</b> — JSON-RPC calls to <c>DataEditorActions</c> on the Java agent,
///     which interact with the BattleScribe data editor scene graph via JavaFX APIs.</item>
///   <item><b>State reads via model access</b> — the Java agent traverses the loaded Java
///     data model directly (no UI parsing) and serializes it to JSON.</item>
///   <item><b>Setup via file staging</b> — game system and catalogue XML files are generated by
///     <see cref="CatXmlGenerator"/> and written to the BS data directory via
///     <see cref="BsUiDataStaging"/>, then loaded by the editor at startup.</item>
/// </list>
/// </para>
/// <para>
/// <b>Engine name in specs</b>: <c>battlescribe-ui</c>. Use this in spec YAML
/// <c>engines</c> field overrides when BattleScribe-specific behavior differs from
/// other engines.
/// </para>
/// <para>
/// <b>Current status</b>: fully implemented. The Java-side <c>DataEditorActions</c> supports
/// load / addEntry / removeEntry / setField / addLink / getDataState; the conformance suite
/// passes against this engine. A <see cref="NotSupportedException"/> is only raised if a new
/// C#-side <c>editorXxxAction</c> is invoked before its Java counterpart exists. Use
/// <see cref="BsGameDataUiProbe"/> to inspect the data editor UI when adding actions.
/// </para>
/// <para>
/// <b>Timeout architecture</b> — same as <see cref="BsUiRosterEngine"/>:
/// <list type="bullet">
///   <item><b>AgentClient.CallTimeout (90s for actions)</b> — Max time for a single JSON-RPC round-trip.</item>
///   <item><b>FX thread dispatch (60s)</b> — Java agent's executeOnFxThread timeout.</item>
///   <item><b>Window wait (30s)</b> — waitForWindow timeout for dialog transitions.</item>
/// </list>
/// </para>
/// </summary>
public sealed class BsGameDataUiEngine : IGameDataEngine
{
    private static readonly JsonSerializerOptions JsonOptions = new() { PropertyNameCaseInsensitive = true };

    private const int WindowWaitMs = 30_000;

    /// <summary>
    /// How long one <see cref="AgentClient.ProbeFxThreadAsync"/> call is given before the instance
    /// is called wedged and warm-start reuse is refused.
    /// </summary>
    private static readonly TimeSpan FxProbeTimeout = TimeSpan.FromSeconds(2);

    private readonly BsUiOptions _options;

    /// <summary>Held for the engine's life; one made per Setup would have nothing to retire.</summary>
    private readonly BsUiDataStaging _dataStaging = new();

    private BsRosterApp? _app;
    private AgentClient? _client;
    private string? _specId;
    private string? _gameSystemId;
    private bool _disposed;

    /// <summary>
    /// Names the staged file for a mid-spec load whose payload is too broken to carry a root id.
    /// Counted rather than fixed so two such loads in one spec do not overwrite each other — the
    /// editor deletes a file it finds corrupt, and a reused name would have the second load racing
    /// the first one being removed.
    /// </summary>
    private int _unnamedLoadCount;

    /// <summary>Engine name constant for per-engine spec overrides.</summary>
    public const string EngineName = "battlescribe-ui";

    /// <summary>
    /// Mirrors <c>DataEditorActions.ADAPTER_GAP</c>: the agent stamps this on a failure it raised
    /// because it did not know what to do, so this side can call it a harness fault instead of an
    /// engine refusal. Without it an unhandled dialog reaches the classifier as an ordinary
    /// exception, whose remainder rule is <c>Engine</c> — and every <c>expectFailure</c> spec on
    /// this lane would pass on the agent giving up.
    /// </summary>
    private const string AgentGapMarker = "[bs-ui-agent-gap] ";

    /// <summary>
    /// When true, <see cref="Cleanup"/> preserves the running app and agent connection
    /// so subsequent <see cref="Setup"/> calls reuse the same JVM instance (warm start).
    /// </summary>
    public bool KeepAlive { get; set; }

    public BsGameDataUiEngine(BsUiOptions options)
    {
        _options = options;
    }

    public void SetTestContext(string specId) => _specId = specId;

    public IReadOnlyList<string> Setup(ProtocolGameSystem gameSystem, ProtocolCatalogue[] catalogues)
        => RunAsync(() => SetupAsync(gameSystem, catalogues));

    public void OpenFile(string id)
        => RunAsync(() => OpenFileAsync(id));

    /// <summary>
    /// Open the selected file through the Data Editor's real open path (the same load + display the
    /// File→Open menu runs after the native picker, which can't be driven in-process). Setup stages
    /// every same-system file to the data directory and opens a primary default; this re-opens the
    /// requested one as the active document. The staged path is <c>{id}.cat</c> (or the game
    /// system's <c>system.gst</c>), matching <see cref="BuildXmlFiles"/>.
    /// </summary>
    private async Task OpenFileAsync(string id)
    {
        if (_app is null)
        {
            throw new InvalidOperationException("openFile: engine not set up.");
        }

        var gsDir = Path.Combine(_app.DataDirectoryPath, _gameSystemId ?? "");
        var path = id == _gameSystemId
            ? Path.Combine(gsDir, "system.gst")
            : Path.Combine(gsDir, $"{id}.cat");
        // A second game system loaded mid-spec is staged as {id}.gst, not as the setup system's
        // system.gst, so it is reachable by id here too.
        if (!File.Exists(path))
        {
            path = Path.Combine(gsDir, $"{id}.gst");
        }

        if (!File.Exists(path))
        {
            throw new SpecAddressingException(
                $"openFile: no staged file for id '{id}' (expected {Path.Combine(gsDir, $"{id}.cat")}).");
        }

        await CallActionAsync("gamedataOpenFileAction", new JsonObject { ["path"] = path });
    }

    public GameDataActionOutputs AddEntry(string parentId, string entryType, string? name = null, string? id = null)
        => RunAsync(() => CallActionAsync<GameDataActionOutputs>("gamedataAddEntryAction", new JsonObject
        {
            ["parentId"] = parentId,
            ["entryType"] = entryType,
            ["name"] = name,
            ["entryId"] = id,
        }));

    public void RemoveEntry(string entryId)
        => RunAsync(() => CallActionAsync("gamedataRemoveEntryAction", new JsonObject
        {
            ["entryId"] = entryId,
        }));

    public void SetField(string entryId, string field, string? value)
        => RunAsync(() => CallActionAsync("gamedataSetFieldAction", new JsonObject
        {
            ["entryId"] = entryId,
            ["field"] = field,
            ["value"] = value,
        }));

    public void SetCost(string entryId, string costTypeId, string? value)
        => RunAsync(() => CallActionAsync("gamedataSetCostAction", new JsonObject
        {
            ["entryId"] = entryId,
            ["field"] = costTypeId,
            ["value"] = value,
        }));

    public void SetCharacteristic(string entryId, string nameOrTypeId, string? value)
        => RunAsync(() => CallActionAsync("gamedataSetCharacteristicAction", new JsonObject
        {
            ["entryId"] = entryId,
            ["field"] = nameOrTypeId,
            ["value"] = value,
        }));

    public GameDataActionOutputs AddLink(string parentId, string linkType, string targetId, string? id = null)
        => RunAsync(() => CallActionAsync<GameDataActionOutputs>("gamedataAddLinkAction", new JsonObject
        {
            ["parentId"] = parentId,
            ["linkType"] = linkType,
            ["targetId"] = targetId,
            ["entryId"] = id,
        }));

    public void Reload()
        => RunAsync(() => CallActionAsync("gamedataSaveAndReloadAction", []));

    public string ExportActiveFile()
        => RunAsync(ExportActiveFileAsync);

    private async Task<string> ExportActiveFileAsync()
    {
        var result = await ConnectedClient.CallAsync("gamedataExportFileAction");
        return result?["xml"]?.GetValue<string>()
            ?? throw new InvalidOperationException("gamedataExportFileAction returned no xml.");
    }

    public string LoadFile(string xml)
        => RunAsync(() => LoadFileAsync(xml));

    /// <summary>
    /// Load a catalogue/game system from XML: stage it to the data directory and open it through the
    /// Data Editor's real open path. Returns the loaded root id.
    /// <para>
    /// The staged name matters twice over. It has to match <see cref="OpenFileAsync"/>'s id-to-path
    /// mapping, so a later <c>openFile</c> by id finds this file; and it must never be a name setup
    /// staged, because the editor <b>deletes</b> a file it finds corrupt — staging a broken game
    /// system as <c>system.gst</c> would take the spec's own game system with it.
    /// </para>
    /// <para>
    /// A payload whose root id cannot be read is staged anyway, under a name derived from the spec.
    /// It used to be rejected here, which meant the one class of file this lane most needs to ask the
    /// editor about — one too broken to name itself — was refused by the driver before the app ever
    /// saw it, and the refusal under test arrived as a harness error (#268).
    /// </para>
    /// </summary>
    private async Task<string> LoadFileAsync(string xml)
    {
        if (_app is null)
        {
            throw new InvalidOperationException("LoadFile: engine not set up.");
        }

        var (id, isGameSystem) = ParseRoot(xml);

        var gsDir = Path.Combine(_app.DataDirectoryPath, _gameSystemId ?? "");
        Directory.CreateDirectory(gsDir);
        var extension = isGameSystem ? "gst" : "cat";
        var fileName = id.Length > 0
            ? $"{id}.{extension}"
            : $"{_specId ?? "spec"}-load-{++_unnamedLoadCount}.{extension}";
        var path = Path.Combine(gsDir, fileName);
        await File.WriteAllTextAsync(path, xml);

        await CallActionAsync("gamedataOpenFileAction", new JsonObject { ["path"] = path });
        return id;
    }

    /// <summary>
    /// Reads the root element's name and <c>id</c> from a payload that may not be well-formed.
    /// <para>
    /// The root is whatever element comes first, matched by shape rather than by name, because
    /// whether the name is acceptable is the app's question and not this driver's. The Data Editor
    /// does check it — a <c>&lt;roster&gt;</c> root comes back <c>Invalid data XML</c> — and that
    /// refusal is a conformance result worth having (see <c>load-wrong-root-element</c>, where the
    /// in-process reader gives the opposite answer). Matching only <c>catalogue|gameSystem</c> here
    /// pre-empted it: the file failed in this method, so the app was never asked.
    /// </para>
    /// <para>
    /// Whether this is a game system is decided by a <c>&lt;gameSystem</c> element appearing at all,
    /// not by a complete root tag — the same test <c>BattleScribeGameDataEngine.LoadFile</c> makes,
    /// deliberately, because the two BattleScribe lanes must ask the same reader about the same
    /// payload or they are not comparable. A truncated game system never closes its root tag, so the
    /// stricter test staged it as a <c>.cat</c> and had the app read a catalogue where the spec said
    /// game system.
    /// </para>
    /// </summary>
    private static (string Id, bool IsGameSystem) ParseRoot(string xml)
    {
        var rootTag = System.Text.RegularExpressions.Regex.Match(xml, @"<\s*[A-Za-z_][\w.:-]*\b[^>]*>").Value;
        var isGameSystem = System.Text.RegularExpressions.Regex.IsMatch(xml, @"<\s*gameSystem\b");
        var id = System.Text.RegularExpressions.Regex.Match(rootTag, @"\bid=""([^""]*)""").Groups[1].Value;
        return (id, isGameSystem);
    }

    public GameDataState GetState()
        => RunAsync(GetStateAsync);

    public IReadOnlyList<ValidationErrorState> GetValidationErrors()
        => RunAsync(GetErrorsAsync);

    private async Task<IReadOnlyList<ValidationErrorState>> GetErrorsAsync()
    {
        ThrowIfDisposed();
        EnsureSetup();

        var result = await ConnectedClient.CallAsync("gamedataGetErrors");
        if (result is null)
        {
            return [];
        }

        var raw = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(result.ToJsonString(), JsonOptions);
        var list = new List<ValidationErrorState>();
        if (raw is not null && raw.TryGetValue("errors", out var errElem) && errElem.ValueKind == JsonValueKind.Array)
        {
            foreach (var e in errElem.EnumerateArray())
            {
                var msg = e.TryGetProperty("message", out var m) ? m.GetString() ?? "" : "";
                list.Add(new ValidationErrorState(msg));
            }
        }

        return list;
    }

    public void Cleanup()
        => RunAsync(() => CleanupAsync());

    public void Dispose()
    {
        if (_disposed)
        {
            return;
        }

        _disposed = true;
        try
        {
            CleanupAsync(force: true).GetAwaiter().GetResult();
        }
        catch
        {
            // Best effort during dispose
        }
        GC.SuppressFinalize(this);
    }

    // ─── Private implementation ───────────────────────────────────────────────

    private async Task<IReadOnlyList<string>> SetupAsync(
        ProtocolGameSystem gameSystem,
        ProtocolCatalogue[] catalogues)
    {
        ThrowIfDisposed();
        await CleanupAsync();
        _gameSystemId = gameSystem.Id; // for resolving openFile paths

        try
        {
            // Warm start: reuse running app if available
            if (KeepAlive && _app is not null && _client is not null)
            {
                try
                {
                    // Not PingAsync: a wedged FX thread still answers `ping`, so that gate declared
                    // undrivable instances reusable and every action against them then failed.
                    await _client.ProbeFxThreadAsync(FxProbeTimeout);
                    Console.Error.WriteLine("[bs-gamedata-ui] Warm start: reusing existing BattleScribe instance.");
                    var warmFiles = BuildXmlFiles(gameSystem, catalogues);
                    await _dataStaging.StageDataFilesAsync(
                        _app.DataDirectoryPath, gameSystem.Id, warmFiles);
                    await LoadStagedFilesAsync(gameSystem, warmFiles);
                    Console.Error.WriteLine("[bs-gamedata-ui] Warm start: loaded new game data into existing instance.");
                    return [];
                }
                catch
                {
                    Console.Error.WriteLine("[bs-gamedata-ui] Warm start: unresponsive, restarting.");
                    _client?.Dispose();
                    _client = null;
                    if (_app is not null)
                    {
                        await _app.DisposeAsync();
                        _app = null;
                    }
                }
            }

            _app = new BsRosterApp(
                _options.JavaPath,
                _options.RosterEditorJarPath,
                _options.AgentJarPath,
                _options.IsolatedHomePath);

            var files = BuildXmlFiles(gameSystem, catalogues);
            await _dataStaging.StageDataFilesAsync(
                _app.DataDirectoryPath, gameSystem.Id, files);

            await _app.StartAsync();
            _client = await _app.ConnectAsync();
            _ = await _client.PingAsync();

            // BattleScribe Data Editor opens with its main window.
            if (!await _client.WaitForWindowAsync("Data Editor", timeoutMs: WindowWaitMs))
            {
                throw new TimeoutException("Data Editor window did not appear within 30 seconds.");
            }

            // Dismiss startup dialogs (download data? → No)
            await HandleStartupDialogsAsync();

            // Load the staged game data files into the editor.
            await LoadStagedFilesAsync(gameSystem, files);

            return [];
        }
        catch (Exception ex)
        {
            // force: true — a setup-phase failure leaves no usable app (it may have died mid-start,
            // or never reached a stable window), so KeepAlive/warm-reuse is meaningless here. Without
            // force, CleanupAsync would no-op (KeepAlive defaults to true), _app would be silently
            // overwritten by the next cold-start attempt, and the orphaned JVM process would leak.
            await CleanupAsync(force: true);
            return [ex.Message];
        }
    }

    private async Task LoadStagedFilesAsync(
        ProtocolGameSystem gameSystem, IReadOnlyList<(string FileName, string Content)> files)
    {
        var gsDir = Path.Combine(_app!.DataDirectoryPath, gameSystem.Id);
        var gstPath = Path.Combine(gsDir, "system.gst");
        var catPaths = files.Where(f => f.FileName.EndsWith(".cat", StringComparison.Ordinal))
            .Select(f => Path.Combine(gsDir, f.FileName)).ToArray();
        var loadParams = new JsonObject
        {
            ["gstPath"] = gstPath,
            ["catPaths"] = new JsonArray([.. catPaths.Select(p => JsonValue.Create(p))]),
        };
        await CallActionAsync("gamedataLoadFilesAction", loadParams);
    }

    /// <summary>
    /// Dismisses BattleScribe's first-launch "download data?" prompt.
    /// </summary>
    /// <remarks>
    /// Delegates to <see cref="AgentClient.DismissStartupConfirmAsync"/>. This used to be its own
    /// copy — sleep 2000ms, check once, sleep 500ms after firing — and was one of four such copies
    /// across the two engines and two probes, all carrying the same single-sample-at-a-fixed-instant
    /// bug. Both waits are now conditions, in one place.
    /// </remarks>
    private Task HandleStartupDialogsAsync()
    {
        Console.Error.WriteLine("[bs-gamedata-ui] Checking for the startup dialog...");
        return _client!.DismissStartupConfirmAsync();
    }

    private async Task<GameDataState> GetStateAsync()
    {
        ThrowIfDisposed();
        EnsureSetup();

        var result = await ConnectedClient.CallAsync("gamedataGetDataState");
        if (result is null)
        {
            return new GameDataState();
        }

        return DeserializeState(result);
    }

    private static GameDataState DeserializeState(JsonNode node)
    {
        var stateJson = node.ToJsonString();
        var raw = JsonSerializer.Deserialize<Dictionary<string, JsonElement>>(stateJson, JsonOptions);
        if (raw is null)
        {
            return new GameDataState();
        }

        GameSystemDataState? gameSystem = null;
        if (raw.TryGetValue("gameSystem", out var gsElem))
        {
            gameSystem = JsonSerializer.Deserialize<GameSystemDataState>(gsElem.GetRawText(), JsonOptions);
        }

        List<CatalogueDataState> catalogues = [];
        if (raw.TryGetValue("catalogues", out var catElem) && catElem.ValueKind == JsonValueKind.Array)
        {
            catalogues = JsonSerializer.Deserialize<List<CatalogueDataState>>(catElem.GetRawText(), JsonOptions) ?? [];
        }
        else if (raw.TryGetValue("catalogue", out var singleCat) && singleCat.ValueKind == JsonValueKind.Object)
        {
            var cat = JsonSerializer.Deserialize<CatalogueDataState>(singleCat.GetRawText(), JsonOptions);
            if (cat is not null)
            {
                catalogues = [cat];
            }
        }

        return new GameDataState { GameSystem = gameSystem, Catalogues = catalogues };
    }

    private async Task CallActionAsync(string method, JsonObject? parameters)
    {
        ThrowIfDisposed();
        EnsureSetup();
        try
        {
            await ConnectedClient.CallAsync(method, parameters, timeout: ActionCallTimeout);
        }
        catch (AgentException ex) when (ex.Message.Contains("not yet implemented") || ex.Message.Contains("UnsupportedOperationException"))
        {
            throw new NotSupportedException(
                $"[bs-gamedata-ui] {method} is not yet implemented in the Java agent. " +
                $"Run `bs-spec probe --engine battlescribe --ui` to probe the data editor UI, " +
                $"then implement DataEditorActions.{method}(). Agent error: {ex.Message}", ex);
        }
        catch (AgentException ex) when (ex.Message.Contains(AgentGapMarker, StringComparison.Ordinal))
        {
            throw new HarnessFaultException(
                $"[bs-gamedata-ui] the Java agent could not drive {method} and said so: {ex.Message}", ex);
        }
    }

    private async Task<T> CallActionAsync<T>(string method, JsonObject? parameters)
    {
        ThrowIfDisposed();
        EnsureSetup();
        try
        {
            var result = await ConnectedClient.CallAsync(method, parameters, timeout: ActionCallTimeout)
                ?? throw new InvalidOperationException($"{method} returned null result.");

            var json = result.ToJsonString();
            return JsonSerializer.Deserialize<T>(json, JsonOptions)
                ?? throw new InvalidOperationException($"Failed to deserialize {method} result.");
        }
        catch (AgentException ex) when (ex.Message.Contains("not yet implemented") || ex.Message.Contains("UnsupportedOperationException"))
        {
            throw new NotSupportedException(
                $"[bs-gamedata-ui] {method} is not yet implemented in the Java agent. " +
                $"Run `bs-spec probe --engine battlescribe --ui` to probe the data editor UI, " +
                $"then implement DataEditorActions.{method}(). Agent error: {ex.Message}", ex);
        }
        catch (AgentException ex) when (ex.Message.Contains(AgentGapMarker, StringComparison.Ordinal))
        {
            throw new HarnessFaultException(
                $"[bs-gamedata-ui] the Java agent could not drive {method} and said so: {ex.Message}", ex);
        }
    }

    /// <summary>
    /// How long one high-level Java-side action gets — the Data Editor counterpart of
    /// <c>BsUiRosterEngine.ActionCallTimeout</c>, and for the same reason: the Java side runs its own
    /// window waits and state polls, so the call has to outlast them or it reports a deadlock just
    /// before the agent reports what actually happened.
    /// </summary>
    private static readonly TimeSpan ActionCallTimeout = TimeSpan.FromSeconds(90);

    private async Task CleanupAsync(bool force = false)
    {
        if (!force && KeepAlive)
        {
            return;
        }

        _client?.Dispose();
        _client = null;
        if (_app is not null)
        {
            await _app.DisposeAsync();
            _app = null;
        }
    }

    private static IReadOnlyList<(string FileName, string Content)> BuildXmlFiles(
        ProtocolGameSystem gameSystem,
        ProtocolCatalogue[] catalogues)
    {
        var gstXml = CatXmlGenerator.GenerateGameSystemXml(gameSystem);
        var files = new List<(string FileName, string Content)>
        {
            ("system.gst", gstXml)
        };
        if (catalogues.Length > 0)
        {
            var catXmls = CatXmlGenerator.GenerateAllCatalogueXml(gameSystem, catalogues);
            files.AddRange(catXmls.Select(c => (c.FileName, c.Xml)));
        }
        return files;
    }

    private AgentClient ConnectedClient =>
        _client ?? throw new InvalidOperationException("[bs-gamedata-ui] Not connected — call Setup() first.");

    private void EnsureSetup()
    {
        if (_client is null)
        {
            throw new InvalidOperationException("[bs-gamedata-ui] Not initialized — call Setup() first.");
        }
    }

    private void ThrowIfDisposed()
    {
        ObjectDisposedException.ThrowIf(_disposed, this);
    }

    private static T RunAsync<T>(Func<Task<T>> func)
        => func().GetAwaiter().GetResult();

    private static void RunAsync(Func<Task> func)
        => func().GetAwaiter().GetResult();

    // ─── Static factory methods ───────────────────────────────────────────────

    /// <summary>
    /// Locates BattleScribe binary artifacts for constructing a <see cref="BsUiOptions"/> instance.
    /// Returns null if the expected artifacts are not present (setup.ps1 not run).
    /// </summary>
    public static BsUiOptions? FindOptions()
    {
        // Same discovery as BsUiRosterEngine — artifacts in lib/battlescribe/
        var repoRoot = RepoRoot.FromBinaries;
        if (repoRoot is null)
        {
            return null;
        }

        var libDir = Path.Combine(repoRoot, "lib", "battlescribe");

        // BS_UI_JAVA_PATH → repo-local Liberica JDK → bundled platform JRE. See BsUiPaths.
        var javaPath = BsUiPaths.ResolveJavaPath(repoRoot);
        if (javaPath is null)
        {
            return null;
        }

        var dataEditorJar = Path.Combine(libDir, "DataEditor.jar");
        if (!File.Exists(dataEditorJar))
        {
            // Some distributions use a different main JAR name
            dataEditorJar = Directory.GetFiles(libDir, "*.jar").FirstOrDefault() ?? dataEditorJar;
        }

        if (!File.Exists(dataEditorJar))
        {
            return null;
        }

        var agentJar = FindAgentJar(repoRoot);
        if (agentJar is null)
        {
            return null;
        }

        return new BsUiOptions
        {
            JavaPath = javaPath,
            RosterEditorJarPath = dataEditorJar,
            AgentJarPath = agentJar,
        };
    }

    private static string? FindAgentJar(string repoRoot)
    {
        // Standard output path from src/bs-ui-java-agent/build.ps1
        var candidate = Path.Combine(repoRoot, "src", "bs-ui-java-agent", "bs-ui-java-agent.jar");
        return File.Exists(candidate) ? candidate : null;
    }
}
