<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    <CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="10.0.0" />
    <PackageVersion Include="GitHubActionsTestLogger" Version="3.0.3" />
    <PackageVersion Include="IKVM" Version="8.15.0" />
    <PackageVersion Include="JsonSchema.Net" Version="9.2.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageVersion Include="Microsoft.Playwright" Version="1.59.0" />
    <PackageVersion Include="Microsoft.Testing.Platform" Version="2.2.1" />
    <PackageVersion Include="xunit.v3" Version="3.2.2" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
    <PackageVersion Include="Vecc.YamlDotNet.Analyzers.StaticGenerator" Version="17.0.0" />
    <PackageVersion Include="Yaml2JsonNode" Version="3.0.1" />
    <PackageVersion Include="YamlDotNet" Version="17.0.1" />
  </ItemGroup>
</Project>