using BattleScribeSpec.Tests.Profiles;

namespace BattleScribeSpec.Tests;

/// <summary>
/// The test app's entry point: the profile host (<see cref="TestHost"/>) in front of xunit's
/// test-platform runner. The host hands the runner this project's self-registered extensions —
/// generated by Microsoft.Testing.Platform.MSBuild — first, exactly as xunit's own generated entry
/// point would, and then its engine-lane tally.
/// </summary>
/// <remarks>
/// Not named <c>Program</c>: in <c>BattleScribeSpec.Cli.Tests</c> that name would shadow the CLI's own
/// <c>Program</c>, which its tests call, and the two projects' entry points read the same.
/// </remarks>
internal static class TestAppEntryPoint
{
    public static Task<int> Main(string[] args) =>
        TestHost.RunAsync(args, TestProfiles.Tests, SelfRegisteredExtensions.AddSelfRegisteredExtensions);
}
