using BattleScribeSpec.Tests.Profiles;
using Xunit.MicrosoftTestingPlatform;

namespace BattleScribeSpec.Tests;

/// <summary>
/// The test app's entry point: the profile host (<see cref="TestHost"/>) in front of xunit's
/// test-platform runner, which gets this project's self-registered extensions — generated by
/// Microsoft.Testing.Platform.MSBuild — exactly as xunit's own generated entry point would pass them.
/// </summary>
/// <remarks>
/// Not named <c>Program</c>: in <c>BattleScribeSpec.Cli.Tests</c> that name would shadow the CLI's own
/// <c>Program</c>, which its tests call, and the two projects' entry points read the same.
/// </remarks>
internal static class TestAppEntryPoint
{
    public static Task<int> Main(string[] args) =>
        TestHost.RunAsync(args, TestProfiles.Tests,
            static a => TestPlatformTestFramework.RunAsync(a, SelfRegisteredExtensions.AddSelfRegisteredExtensions));
}
