<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BattleScribeSpec.ReferenceAdapter</RootNamespace>
    <AssemblyName>bs-reference-adapter</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BattleScribeSpec.BattleScribe\BattleScribeSpec.BattleScribe.csproj" />
  </ItemGroup>

  <Target Name="CopyIkvmAssemblies" AfterTargets="Build">
    <PropertyGroup>
      <_BattleScribeBinPath>$(ArtifactsPath)\bin\BattleScribeSpec.BattleScribe\$(ArtifactsPivots)\</_BattleScribeBinPath>
    </PropertyGroup>
    <ItemGroup>
      <IkvmDlls Include="$(_BattleScribeBinPath)DataUtils.dll;$(_BattleScribeBinPath)CommonsIo.dll;$(_BattleScribeBinPath)KotlinStdlib.dll;$(_BattleScribeBinPath)KotlinStdlibCommon.dll;$(_BattleScribeBinPath)Stax.dll;$(_BattleScribeBinPath)StaxApi.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(IkvmDlls)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>

</Project>
