<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BattleScribeSpec.ReferenceAdapter</RootNamespace>
    <AssemblyName>bs-reference-adapter</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BattleScribeSpec.BattleScribe\BattleScribeSpec.BattleScribe.csproj" />
  </ItemGroup>

  <Import Project="..\BattleScribeSpec.BattleScribe\BattleScribeIkvmConsumer.targets" />

</Project>
