<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BattleScribeSpec.ReferenceAdapter</RootNamespace>
    <AssemblyName>bs-reference-adapter</AssemblyName>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BattleScribeSpec.Oracle\BattleScribeSpec.Oracle.csproj" />
  </ItemGroup>

  <Target Name="CopyIkvmAssemblies" AfterTargets="Build">
    <PropertyGroup>
      <_OracleBinPath>$(ArtifactsPath)\bin\BattleScribeSpec.Oracle\$(ArtifactsPivots)\</_OracleBinPath>
    </PropertyGroup>
    <ItemGroup>
      <IkvmDlls Include="$(_OracleBinPath)DataUtils.dll;$(_OracleBinPath)CommonsIo.dll;$(_OracleBinPath)KotlinStdlib.dll;$(_OracleBinPath)KotlinStdlibCommon.dll;$(_OracleBinPath)Stax.dll;$(_OracleBinPath)StaxApi.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(IkvmDlls)" DestinationFolder="$(OutputPath)" SkipUnchangedFiles="true" />
  </Target>

</Project>
