using System.Reflection;
using System.Text.RegularExpressions;
using System.Xml.Linq;
using BattleScribeSpec.Tests.Profiles;

namespace BattleScribeSpec.Tests;

/// <summary>
/// <b>Every test project starts through the profile host, and nothing feeds the test app a lane by a
/// side door.</b> <see cref="TestHost"/> holds a command line to its rules only if every way of starting
/// the suites reaches it: each project's entry point calls it, MSBuild hands it the strict zero-tests
/// policy from one place, and no file the platform or the SDK reads on its own — a launch profile, a
/// <c>testconfig.json</c>, a runsettings file — carries arguments, environment or selection nobody sees
/// on the command line.
/// </summary>
/// <remarks>
/// Each check was mutation-checked when written; the mutation is named on each.
/// </remarks>
[Trait("Category", "Lint")]
public sealed class TestHostWiringTests
{
    private static string Root => TestPaths.Root;

    private const string TestsProps = "tests/Directory.Build.props";

    /// <summary>
    /// <b>Every test project lives under <c>tests/</c>, inherits <c>tests/Directory.Build.props</c>, and has
    /// a <c>Program.cs</c> whose <c>Main</c> is one call to
    /// <see cref="TestHost.RunAsync(string[], string, Action{Microsoft.Testing.Platform.Builder.ITestApplicationBuilder, string[]})"/>
    /// naming its own assembly and handing over its generated extensions</b> — and compiles the registry the host reads.
    /// </summary>
    /// <remarks>
    /// <para>
    /// A test project anywhere else, or with a <c>Directory.Build.props</c> of its own in between, would
    /// build without that file: xunit's generated entry point instead of the host, no strict policy on
    /// <c>dotnet test</c>, and <c>-p:TestProfile</c> silently ignored — an unknown MSBuild property is not
    /// an error. A project that sets one of the file's properties itself overrides it the same way. The
    /// test app this check runs in is also asked, by reflection, which method is its entry point.
    /// </para>
    /// <para>
    /// Mutation-checked when written: a <c>Directory.Build.props</c> added in
    /// <c>tests/BattleScribeSpec.Cli.Tests/</c>; <c>XunitAutoGeneratedEntryPoint</c> set to <c>true</c> in a
    /// csproj; Cli.Tests' <c>Program.cs</c> passing <c>TestProfiles.Tests</c>; and the registry link removed
    /// from Cli.Tests (the build fails first, as it should) — each goes red naming the project. The host
    /// registers the engine-lane tally itself, after what <c>Program.cs</c> hands it; a <c>Program.cs</c> that
    /// hands it anything but the generated <c>SelfRegisteredExtensions.AddSelfRegisteredExtensions</c> (the
    /// GitHub reporter, the platform's MSBuild integration) goes red too — mutation-checked with a no-op lambda
    /// in its place.
    /// </para>
    /// </remarks>
    [Fact]
    public void EveryTestProject_InheritsTheTestHostProps()
    {
        var problems = new List<string>();
        var props = XDocument.Load(Path.Combine(Root, TestsProps));
        if (!props.Descendants("Import").Any(static i => (string?)i.Attribute("Project") is { } p
            && p.Contains("GetPathOfFileAbove('Directory.Build.props'", StringComparison.Ordinal)))
        {
            problems.Add($"  {TestsProps} does not import the repository's Directory.Build.props, so the test projects lose every setting in it");
        }

        foreach (var (property, value) in new[] { ("UseMicrosoftTestingPlatformRunner", "true"), ("XunitAutoGeneratedEntryPoint", "false") })
        {
            if (!props.Descendants(property).Any(e => e.Value.Trim() == value && e.Parent?.Attribute("Condition") is null))
            {
                problems.Add($"  {TestsProps} does not set {property} to {value} unconditionally");
            }
        }

        var entryHosts = new Regex(@"TestHost\.RunAsync\(\s*args\s*,\s*TestProfiles\.(\w+)\s*,\s*(.+?)\s*\)\s*;", RegexOptions.Singleline);
        var projects = SolutionProjects.Tests;
        Assert.NotEmpty(projects);
        foreach (var project in projects)
        {
            var name = project.RelativePath;
            if (!name.StartsWith("tests/", StringComparison.Ordinal))
            {
                problems.Add($"  {name} is not under tests/, so it builds without {TestsProps}");
                continue;
            }

            for (var dir = project.Directory; dir != "tests"; dir = Path.GetDirectoryName(dir)!.Replace('\\', '/'))
            {
                if (File.Exists(Path.Combine(Root, dir, "Directory.Build.props")))
                {
                    problems.Add($"  {dir}/Directory.Build.props sits between {name} and {TestsProps}, and MSBuild stops at the first one it finds");
                }
            }

            var csproj = File.ReadAllText(Path.Combine(Root, name));
            foreach (var property in new[]
            {
                "UseMicrosoftTestingPlatformRunner", "XunitAutoGeneratedEntryPoint", "TestingPlatformCommandLineArguments",
                "GenerateTestingPlatformEntryPoint", "IsTestingPlatformApplication", "RunArguments",
            })
            {
                if (csproj.Contains($"<{property}", StringComparison.Ordinal))
                {
                    problems.Add($"  {name} sets {property} itself, overriding {TestsProps}");
                }
            }

            if (project.Directory != "tests" && !Regex.IsMatch(csproj.Replace('\\', '/'), @"<Compile\s+Include=""\.\./TestProfiles/\*\*/\*\.cs"""))
            {
                problems.Add($"  {name} does not compile ../TestProfiles/**/*.cs, the registry and host its entry point calls");
            }

            var program = Path.Combine(Root, project.Directory, "Program.cs");
            if (!File.Exists(program))
            {
                problems.Add($"  {name} has no Program.cs: its entry point is not the profile host");
                continue;
            }

            var call = entryHosts.Match(File.ReadAllText(program));
            var member = call.Success ? call.Groups[1].Value : null;
            var assembly = member is null ? null : typeof(TestProfiles).GetField(member, BindingFlags.Public | BindingFlags.Static)?.GetRawConstantValue() as string;
            if (member is null)
            {
                problems.Add($"  {project.Directory}/Program.cs does not call TestHost.RunAsync(args, TestProfiles.<assembly>, "
                    + "SelfRegisteredExtensions.AddSelfRegisteredExtensions)");
            }
            else if (assembly != project.AssemblyName)
            {
                problems.Add($"  {project.Directory}/Program.cs tells the host it is {assembly ?? member}; the project builds {project.AssemblyName}");
            }

            if (call.Success && call.Groups[2].Value != "SelfRegisteredExtensions.AddSelfRegisteredExtensions")
            {
                problems.Add($"  {project.Directory}/Program.cs hands the host `{call.Groups[2].Value}` instead of "
                    + "SelfRegisteredExtensions.AddSelfRegisteredExtensions, the extensions Microsoft.Testing.Platform.MSBuild generates "
                    + "for the project (the GitHub reporter, the MSBuild integration)");
            }
        }

        var entryPoint = typeof(TestHostWiringTests).Assembly.EntryPoint;
        if (entryPoint?.DeclaringType != typeof(TestAppEntryPoint))
        {
            problems.Add($"  {EngineLanes.Assembly}'s entry point is {entryPoint?.DeclaringType?.FullName ?? "(none)"}.{entryPoint?.Name}, not TestAppEntryPoint.Main");
        }

        Assert.True(problems.Count == 0,
            "Every test project must start through the profile host (tests/TestProfiles/TestHost.cs):\n" + string.Join("\n", problems) + "\n\n"
            + $"{TestsProps} turns off xunit's generated entry point, makes `dotnet test` and `dotnet run` pass the strict "
            + "zero-tests policy, and maps -p:TestProfile; each project's Program.cs hands Main to TestHost.RunAsync with its "
            + "own assembly name and its generated extensions. A project that misses any of that runs without the rules the host enforces.");
    }

    /// <summary>
    /// <b><c>tests/Directory.Build.props</c> is the one setter of <c>TestingPlatformCommandLineArguments</c>,
    /// it sets <c>--zero-tests-policy strict</c> unconditionally, nothing else passes a zero-tests policy,
    /// and nothing sets <c>RunArguments</c></b> — the other property the SDK hands a test app on both
    /// <c>dotnet test</c> and <c>dotnet run</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The strict policy is what fails a run that executed nothing — the lane that matched no test, and
    /// the lane whose only selected test skipped (<c>Engine=FrozenNrRoster&amp;DisplayName~kitchen-sink</c>
    /// once selected exactly one self-skipping sequential row: <c>Passed: 0, Skipped: 1</c>,
    /// exit 0, green on every PR while that suite had no coverage). It used to be a wrapper script that
    /// read TRX counters; now it is the platform's own exit 8, from exactly two places: this property for
    /// <c>dotnet test</c> and <c>dotnet run</c>, and the host for a run started any other way. A second
    /// setter could drop it (a property assignment that does not append replaces the value), and a
    /// second policy on a command line either duplicates it — refused — or, on a direct run, replaces it.
    /// The host's half is checked here too, by asking it what it would run.
    /// </para>
    /// <para>
    /// Read: every MSBuild file of the repository, and every file that invokes the tests
    /// (<see cref="ConcurrencyConfigurationDriftTests.TestInvocationFiles"/>: workflows, actions, scripts,
    /// tools, docker). Mutation-checked when written: <c>-p:TestingPlatformCommandLineArguments=x</c> on a
    /// CI step; <c>&lt;RunArguments&gt;</c> in the Tests csproj; <c>--zero-tests-policy allow-skipped</c> on
    /// a CI step; the strict policy moved under a condition in the props file; and the host's step that
    /// adds it to a direct run deleted — each goes red.
    /// </para>
    /// </remarks>
    [Fact]
    public void StrictZeroTestPolicy_HasOneSetter()
    {
        var problems = new List<string>();
        var msbuild = MsBuildFiles().ToList();
        Assert.Contains(msbuild, static f => Relative(f) == TestsProps);

        foreach (var file in msbuild)
        {
            var relative = Relative(file);
            var doc = XDocument.Load(file);
            foreach (var element in doc.Descendants().Where(static e => e.Name.LocalName is "TestingPlatformCommandLineArguments" or "RunArguments"))
            {
                if (relative != TestsProps || element.Name.LocalName == "RunArguments")
                {
                    problems.Add($"  {relative}: sets {element.Name.LocalName}; {TestsProps} is its one setter{(element.Name.LocalName == "RunArguments" ? " (and sets no RunArguments)" : "")}");
                }
            }
        }

        var props = XDocument.Load(Path.Combine(Root, TestsProps));
        if (!props.Descendants("TestingPlatformCommandLineArguments").Any(static e => e.Parent?.Attribute("Condition") is null
            && e.Value.Contains("--zero-tests-policy strict", StringComparison.Ordinal)
            && e.Value.TrimStart().StartsWith("$(TestingPlatformCommandLineArguments)", StringComparison.Ordinal)))
        {
            problems.Add($"  {TestsProps} does not append --zero-tests-policy strict to TestingPlatformCommandLineArguments unconditionally");
        }

        var property = new Regex(@"\b(?:TestingPlatformCommandLineArguments|RunArguments)\b", RegexOptions.CultureInvariant);
        var policy = new Regex(@"--zero-tests-policy\b", RegexOptions.CultureInvariant);
        var invocations = ConcurrencyConfigurationDriftTests.TestInvocationFiles(Root);
        foreach (var file in invocations.Where(f => !msbuild.Contains(f, StringComparer.OrdinalIgnoreCase)))
        {
            var lines = File.ReadAllLines(file);
            for (var i = 0; i < lines.Length; i++)
            {
                if (lines[i].TrimStart().StartsWith('#'))
                {
                    continue;
                }

                if (property.Match(lines[i]) is { Success: true } p)
                {
                    problems.Add($"  {Relative(file)}:{i + 1}: names {p.Value} — on a command line or in the environment, MSBuild takes it as the property");
                }

                if (policy.IsMatch(lines[i]))
                {
                    problems.Add($"  {Relative(file)}:{i + 1}: passes a zero-tests policy of its own");
                }
            }
        }

        var direct = TestHost.Resolve(["--list-tests"], TestProfiles.Tests, static _ => null).Arguments;
        if (direct.Count(static a => a == "--zero-tests-policy") != 1 || !direct.Contains("strict"))
        {
            problems.Add($"  TestHost does not give a direct run --zero-tests-policy strict exactly once: {string.Join(" ", direct)}");
        }

        Assert.True(problems.Count == 0,
            "The strict zero-tests policy must come from one MSBuild setter and the host, and from nowhere else:\n"
            + string.Join("\n", problems) + "\n\n"
            + "It is what fails a lane that executed nothing (exit 8). Append to TestingPlatformCommandLineArguments only in "
            + $"{TestsProps}, and leave the policy off command lines: `dotnet test` and `dotnet run` already carry it, and the "
            + "host adds it to every other run.");
    }

    /// <summary>
    /// <b><c>-p:TestProfile=x</c> reaches the host as <c>--test-profile x</c>, and <c>-p:RunSettingsFilePath</c>
    /// as <c>--settings</c></b>: <c>tests/Directory.Build.props</c> appends each to
    /// <c>TestingPlatformCommandLineArguments</c> when the property is set.
    /// </summary>
    /// <remarks>
    /// <para>
    /// An MSBuild property nothing reads is not an error, so without the first mapping
    /// <c>dotnet test -p:TestProfile=pre-push</c> runs every test of both projects, unprofiled, and exits 0
    /// — and <c>-p:TestProfile=nope</c> does too, where the host would have refused an unknown profile.
    /// Nothing else would notice: CI's one <c>dotnet test</c> step runs <c>cli</c>, the whole of its
    /// project, so it passes with the profile or without. Without the second, the VSTest habit
    /// <c>-p:RunSettingsFilePath=x</c> is ignored instead of refused with a message naming the replacement.
    /// </para>
    /// <para>
    /// Mutation-checked when written: each of the two property groups deleted, the first one's condition
    /// misspelt (<c>'$(TestProfil)' != ''</c>), and its value no longer appending
    /// (<c>--test-profile $(TestProfile)</c> alone, which drops the strict policy) — each goes red naming
    /// the mapping.
    /// </para>
    /// </remarks>
    [Fact]
    public void MsBuildProperties_ReachTheHost()
    {
        var props = XDocument.Load(Path.Combine(Root, TestsProps));
        var problems = new List<string>();
        foreach (var (property, appended, otherwise) in new[]
        {
            ("TestProfile", "--test-profile $(TestProfile)", "runs every test unprofiled and exits 0, an unknown profile included"),
            ("RunSettingsFilePath", "--settings \"$(RunSettingsFilePath)\"", "is ignored instead of refused, naming -p:TestProfile"),
        })
        {
            var condition = $"'$({property})' != ''";
            var mapped = props.Descendants("TestingPlatformCommandLineArguments").Any(e =>
                Squeeze((string?)e.Attribute("Condition") ?? (string?)e.Parent?.Attribute("Condition")) == condition
                && e.Value.TrimStart().StartsWith("$(TestingPlatformCommandLineArguments)", StringComparison.Ordinal)
                && e.Value.Contains(appended, StringComparison.Ordinal));
            if (!mapped)
            {
                problems.Add($"  {TestsProps} does not append `{appended}` to $(TestingPlatformCommandLineArguments) under the condition "
                    + $"{condition}, so `dotnet test -p:{property}=…` {otherwise}");
            }
        }

        Assert.True(problems.Count == 0,
            "The MSBuild properties the test host is driven by must reach it:\n" + string.Join("\n", problems) + "\n\n"
            + "The host only sees the test app's own command line; tests/Directory.Build.props is what turns an MSBuild property into "
            + "an option on it. Keep each mapping as a property group conditioned on the property being set, appending to "
            + "the existing value.");

        static string? Squeeze(string? text) => text is null ? null : Regex.Replace(text.Trim(), @"\s+", " ");
    }

    /// <summary>
    /// <b>No file the platform or the SDK reads on its own feeds the test app</b>: no
    /// <c>launchSettings.json</c> or <c>*.run.json</c> under <c>tests/</c>, no <c>testconfig.json</c> or
    /// <c>*.testconfig.json</c> under <c>tests/</c>, and no <c>*.runsettings</c> anywhere in the repository.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <c>dotnet test</c> and <c>dotnet run</c> apply a launch profile's arguments and environment unless
    /// told not to, so a <c>launchSettings.json</c> would set a variable — or a filter — on
    /// every local run with nothing on the command line to show it. The platform reads
    /// <c>&lt;assembly&gt;.testconfig.json</c> (built from a project's <c>testconfig.json</c>), which can carry
    /// platform and xunit options a profile does not know about. A <c>.runsettings</c> file is read by
    /// nothing now; one left in the tree reads as a lane, and is how the suites used to be configured.
    /// </para>
    /// <para>
    /// Mutation-checked when written: an empty <c>tests/Properties/launchSettings.json</c>, a
    /// <c>tests/testconfig.json</c> and a <c>docs/x.runsettings</c> each go red naming the file. A
    /// <c>x.runsettings</c> inside a nested checkout (a directory under <c>.claude/worktrees/</c> holding a
    /// <c>.git</c> file) stays green, and one directly in <c>.claude/</c> goes red.
    /// </para>
    /// <para>
    /// <b>This checkout's files only.</b> Agent worktrees live inside the main checkout, under the
    /// gitignored <c>.claude/worktrees/</c>, each a full checkout of its own — and one based on a commit
    /// from before the runsettings were deleted still has them. Walking into those made the main checkout's
    /// pre-push red for files that are not in it. A directory with a <c>.git</c> of its own (a worktree, a
    /// submodule, a nested repository) is somebody else's checkout, and is not walked.
    /// </para>
    /// </remarks>
    [Fact]
    public void NoImplicitTestInputs()
    {
        var underTests = CheckoutFiles(Path.Combine(Root, "tests")).Select(Relative).ToList();
        Assert.Contains(TestsProps, underTests);

        var problems = underTests
            .Where(static f => Path.GetFileName(f) is "launchSettings.json" or "testconfig.json"
                || f.EndsWith(".run.json", StringComparison.OrdinalIgnoreCase)
                || f.EndsWith(".testconfig.json", StringComparison.OrdinalIgnoreCase))
            .Select(static f => $"  {f}")
            .ToList();

        string[] excluded = [".deps", "artifacts", "lib", ".git", ".testdata"];
        var runsettings = CheckoutFiles(Root, excluded)
            .Where(static f => f.EndsWith(".runsettings", StringComparison.OrdinalIgnoreCase))
            .Select(Relative);
        problems.AddRange(runsettings.Select(static f => $"  {f}"));

        Assert.True(problems.Count == 0,
            "These files would configure the test app without appearing on any command line:\n" + string.Join("\n", problems) + "\n\n"
            + "A lane is a test profile (tests/TestProfiles/TestProfiles.cs), resolved by the test app's entry point. A launch "
            + "profile, a testconfig.json or a runsettings file is a second record of a lane next to it — one the host never "
            + "sees. Delete the file, and put what it meant into a profile.");
    }

    /// <summary>
    /// Every file under <paramref name="directory"/> that belongs to this checkout: build output and package
    /// folders (<c>bin</c>, <c>obj</c>, <c>node_modules</c>, <c>TestResults</c>) are not walked at any depth,
    /// <paramref name="excludedAtTop"/> names top-level folders to leave out, and neither is a nested
    /// checkout — a directory below <paramref name="directory"/> with a <c>.git</c> file or folder of its own.
    /// </summary>
    private static IEnumerable<string> CheckoutFiles(string directory, params string[] excludedAtTop)
    {
        string[] generated = ["bin", "obj", "node_modules", "TestResults"];
        var pending = new Stack<string>();
        pending.Push(directory);
        while (pending.Count > 0)
        {
            var current = pending.Pop();
            foreach (var file in Directory.EnumerateFiles(current))
            {
                yield return file;
            }

            foreach (var child in Directory.EnumerateDirectories(current))
            {
                var name = Path.GetFileName(child);
                var skipped = generated.Contains(name, StringComparer.OrdinalIgnoreCase)
                    || (current == directory && excludedAtTop.Contains(name, StringComparer.OrdinalIgnoreCase))
                    || File.Exists(Path.Combine(child, ".git")) || Directory.Exists(Path.Combine(child, ".git"));
                if (!skipped)
                {
                    pending.Push(child);
                }
            }
        }
    }

    /// <summary>The repository's own MSBuild files: the root's, and those under its source trees.</summary>
    private static IEnumerable<string> MsBuildFiles()
    {
        string[] extensions = [".csproj", ".props", ".targets"];
        string[] trees = ["src", "tests", "tools", "docker"];
        return Directory.EnumerateFiles(Root)
            .Concat(trees
                .Select(d => Path.Combine(Root, d))
                .Where(Directory.Exists)
                .SelectMany(static d => Directory.EnumerateFiles(d, "*", SearchOption.AllDirectories)))
            .Where(f => extensions.Contains(Path.GetExtension(f), StringComparer.OrdinalIgnoreCase))
            .Where(static f => !Relative(f).Split('/').Any(static s => s is "bin" or "obj"));
    }

    private static string Relative(string path) => Path.GetRelativePath(Root, path).Replace('\\', '/');
}
