<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>BattleScribeSpec.Runner</RootNamespace>
    <AssemblyName>bs-spec-runner</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BattleScribeSpec.TestKit\BattleScribeSpec.TestKit.csproj" />
  </ItemGroup>

</Project>
