using BattleScribeSpec.Tests.Profiles;
using Xunit.MicrosoftTestingPlatform;

namespace BattleScribeSpec.Cli.Tests;

/// <summary>
/// The test app's entry point: the profile host (<see cref="TestHost"/>) in front of xunit's
/// test-platform runner, which gets this project's self-registered extensions — generated by
/// Microsoft.Testing.Platform.MSBuild — exactly as xunit's own generated entry point would pass them.
/// </summary>
/// <remarks>
/// Not named <c>Program</c>: that name would shadow <c>BattleScribeSpec.Cli.Program</c>, which these
/// tests call.
/// </remarks>
internal static class TestAppEntryPoint
{
    public static Task<int> Main(string[] args) =>
        TestHost.RunAsync(args, TestProfiles.Cli,
            static a => TestPlatformTestFramework.RunAsync(a, SelfRegisteredExtensions.AddSelfRegisteredExtensions));
}
