using BattleScribeSpec.Tests.Profiles;

namespace BattleScribeSpec.Cli.Tests;

/// <summary>
/// The test app's entry point: the profile host (<see cref="TestHost"/>) in front of xunit's
/// test-platform runner. The host hands the runner this project's self-registered extensions —
/// generated by Microsoft.Testing.Platform.MSBuild — first, exactly as xunit's own generated entry
/// point would, and then its engine-lane tally.
/// </summary>
/// <remarks>
/// Not named <c>Program</c>: that name would shadow <c>BattleScribeSpec.Cli.Program</c>, which these
/// tests call.
/// </remarks>
internal static class TestAppEntryPoint
{
    public static Task<int> Main(string[] args) =>
        TestHost.RunAsync(args, TestProfiles.Cli, SelfRegisteredExtensions.AddSelfRegisteredExtensions);
}
